### ISSUE TITLE
erreur validation magento2 Magento ver. 2.4.3-p2

### ISSUE THREAD

**Issue by royalkaroma** [pfpayments/magento-2.2#1]
Synchronizing with PostFinance Checkout failed: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'zb1un_app_magento.vs38_postfinancecheckout_payment_method_configuration' doesn't exist, query was: SELECT `main_table`.* FROM `vs38_postfinancecheckout_payment_method_configuration` AS `main_table` WHERE ((`state` IN(1, 2, 3)))

**Comment by royalkaroma** [comment]
![Capture](https://user-images.githubusercontent.com/36032214/189497341-0f10d23c-0285-410b-8b8e-5ae6ecc568b7.PNG)

**Comment by royalkaroma** [comment]
the name postfinancecheckout_payment dosint exist any ware only the name of developer

**Comment by theodorspringwallee** [comment]
Dear [royalkaroma](https://github.com/royalkaroma), this was a BUG.

Please re-install the plugin in its newest version completely.
